config/routes.rb
Rails.application.routes.draw do
  get 'licenses/index'

  get 'licenses/edit'

  get 'licenses/show'

  get 'licenses/create'

  get 'licenses/new'

  get 'licenses/update'

  get 'licenses/destroy'

  get 'home/index'

  get 'user/index'

  get 'user/profile'

  get 'user/settings'

  devise_for :users

  root 'home#index'

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
end

app/models/license.rb
class License < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/violation.rb
class Violation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  def index
    @licenses = License.order("created_at desc").page(params[:page]).per_page(20)
  end

  def edit
     @licenses = current_user.licenses.find(params[:id])
  end

  def show
    @licenses = License.find(params[:id])
  end

  def create
    @licenses = current_user.licenses.new(params[:licenses])
  end

  def new
     @licenses = current_user.licenses.new
  end

  def update
     @licenses = current_user.pins.find(params[:id])

    respond_to do |format|
      if @licenses.update_attributes(params[:licenses])
        format.html { redirect_to @licenses, notice: 'License was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @licenses.errors, status: :unprocessable_entity }
  end

  def destroy
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def profile
  end

  def settings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<head>
  <title>LicenseTrack</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <%= link_to "License Tracker",  root_path, :class => "brand" %>
    <ul class="nav">
      <li class="active"><a href="#">Home</a></li>
      <li><%= link_to "Dashboard",  user_index_path %></li>
      <li><%= link_to "Sign In",  new_user_session_path %></li>
      <li><%= link_to "Sign Up",  new_user_registration_path %></li>
      <li><a href="#">Link</a></li>

      <li><a href="#">Settings</a></li>
    </ul>
  </div>
</div>

<section class="hero hero--video" style="background-image: url(https://gathercontent.com/wp-content/uploads/2015/07/normal_1-1000x666.jpg)">
<div class="hero__video-wrapper">
<video autoplay="" class="hero__video" loop="loop" preload="auto" width="400" style="width:100%;">
<source media="only screen and (min-width: 600px)" src="http://i.istockimg.com/video_passthrough/23721092/153/23721092.mp4" type="video/mp4; codecs=avc1.64001E">
<source media="only screen and (min-width: 600px)" src="#" type="video/ogg; codecs=theora">
<source media="only screen and (min-width: 600px)" src="#" type="webm; codecs=vp8">
</video>
</div>
<div class="hero__overlay overlay overlay--primary">
<div class="vcenter">
<div class="vcenter__content">
<div class="container">
<div class="hero__content section section--huge">
<h1 class="homepage-tag">Never Miss a License Renewal Date again!</h1>
<div class="container container--medium container--left">
<p class="homepage-tagline">No more sorting through endless filing cabinents or being frustrated by outdated software.</p>
<a href="#" class="btn btn-primary btn-large">Start my 30-day free trial</a>
</div>
</div>
</div>
</div>
</div>
</div>
</section>


<div class="container">
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<html>
<head>
  <title>LicenseTrack</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/licenses/create.html.erb
<h1>Licenses#create</h1>
<p>Find me in app/views/licenses/create.html.erb</p>

app/views/licenses/destroy.html.erb
<h1>Licenses#destroy</h1>
<p>Find me in app/views/licenses/destroy.html.erb</p>

app/views/licenses/edit.html.erb
<h1>Licenses#edit</h1>
<p>Find me in app/views/licenses/edit.html.erb</p>

app/views/licenses/index.html.erb
<h1>Licenses#index</h1>
<p>Find me in app/views/licenses/index.html.erb</p>

app/views/licenses/new.html.erb
<h1>Licenses#new</h1>
<p>Find me in app/views/licenses/new.html.erb</p>

app/views/licenses/show.html.erb
<h1>Licenses#show</h1>
<p>Find me in app/views/licenses/show.html.erb</p>

app/views/licenses/update.html.erb
<h1>Licenses#update</h1>
<p>Find me in app/views/licenses/update.html.erb</p>

app/views/user/index.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <%= link_to "License Tracker",  root_path,  :class => "brand" %>
    <ul class="nav">
      <li class="active"><a href="#">Home</a></li>
      <li><%= link_to "Dashboard",  user_index_path %></li>
      <li><%= link_to "Sign In",  new_user_session_path %></li>
      <li><%= link_to "Sign In",  new_user_registration_path %></li>
      <li><a href="#">Settings</a></li>
    </ul>
  </div>
</div>

<div class="sidebar">
	<ul>
	  <li><a href="#">Dashboard Link 1</a></li>
	  <li><a href="#">Dashboard Link 2</a></li>
	  <li><a href="#">Dashboard Link 3</a></li>
	</ul>
</div>
	
<div class="main">
	
	<h1>Company Name</h1>
	<p>Find me in app/views/user/index.html.erb</p>

Test 1
<div style="height:200px;">
	<ul class="nav nav-pills">
  <li class="active">
    <a href="#">Home</a>
  </li>
  <li><a href="#">Upcoming Licenses</a></li>
  <li><a href="#">Newly Added</a></li>
  <li><a href="#">+ Create New Notification</a></li>
</ul>
</div>



<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" data-src="holder.js/64x64">
  </a>
  <div class="media-body">
    <h4 class="media-heading">Media heading</h4>
    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
 
    <!-- Nested media object -->
    <div class="media">
      ...
    </div>
  </div>
</div>

app/views/user/profile.html.erb
<h1>User#profile</h1>
<p>Find me in app/views/user/profile.html.erb</p>

app/views/user/settings.html.erb
<h1>User#settings</h1>
<p>Find me in app/views/user/settings.html.erb</p>